#2 Update main structure
front-end-by-rimantas/25-grupe-portfolio-neuron pull request #17
Opened 2021-03-30 08:23 UTC by AisteKara

- Updated title
 - uploaded logo image
 - removed .gitempty file from img folder
 - added HTML sections as comments (ONLY)
 - updated CSS file by adding comments for sections "custom-home.css"
 - updated JS file by adding comments for sections "mainHome.js"

2021-03-30 08:27 UTC, kappowas submitted a review, later dismissed
not bad ;]

2021-03-30 11:03 UTC, kamidem requested changes
perzvelgiau vel struktura is dev tools, siulau kelis pakeitimus:

- navigation, tai cia meniu? pamirsau is vakar. manau galima isimti
- virs header ten yra idetas tas loading page, tai gal ir mes ji virsuj i kelkim?
- po header man atrodo galima atskirai idet hero, nes pagal dev tools tai atskiri elementai
- tada galbut siek tiek pervadinkim sekcijas kad butu aiskiau nei kas teksto pradzia? (power your creativity -> about; we create -> about 2 ar about video (kaip ten yra);
- subscription ten yra latest project sekcijoj, gal sujunkim?
- gal idedam partner section po projects?
- ir gal dar parasom kur start kur end kiekvienos section?

2021-03-30 11:03 UTC, kamidem commented on css/custom-home.css
> +/* contacts */
perzvelgiau vel struktura is dev tools, siulau kelis pakeitimus:
- navigation, tai cia meniu? pamirsau is vakar. manau galima isimti
- virs header ten yra idetas tas loading page, tai gal ir mes ji virsuj i kelkim?
- po header man atrodo galima atskirai idet hero, nes pagal dev tools tai atskiri elementai
- tada galbut siek tiek pervadinkim sekcijas kad butu aiskiau nei kas teksto pradzia? (power your creativity -> about; we create -> about 2 ar about video (kaip ten yra); 
- subscription ten yra latest project sekcijoj, gal sujunkim?
- gal idedam partner section po projects?

2021-03-30 12:01 UTC, kamidem approved these changes

2021-03-30 12:23 UTC, kappowas approved these changes
manau gan tvarkingai ir teisingai padaryta comentarai

2021-03-30 12:24 UTC, merged

2021-03-30 12:26 UTC, Liudvikask1 reviewed
Viskas, kaip ir, savo vietose.

2021-03-31 07:05 UTC, Lukasj17 reviewed
im good with that