chatbox initial commit
front-end-by-rimantas/25-grupe-portfolio-neuron pull request #54
Opened 2021-04-13 21:39 UTC by Liudvikask1

Initial chatbox commit

2021-04-13 22:38 UTC, AisteKara requested changes
Nicely done, just needs z-index on chat-box popup and a transition

2021-04-14 08:52 UTC, Liudvikask1 commented
Added z-index, some other slight adjustments. Unable to add transition as it doesn't work with property "display:"

2021-04-14 08:58 UTC, AisteKara approved these changes

2021-04-14 12:29 UTC, kappowas approved these changes

2021-04-14 12:29 UTC, merged